# Generated by Django 4.1.2 on 2023-01-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Jop",
            new_name="Job",
        ),
    ]
