# Generated by Django 4.1.2 on 2023-01-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_rename_jop_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part Time"),
                    ("together", "Full and Part time"),
                ],
                default="",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
