# Generated by Django 4.1.2 on 2023-01-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_job_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="published_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="vacancy",
            field=models.IntegerField(default=1),
        ),
    ]
