# Generated by Django 4.1.2 on 2023-01-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_job_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(default=1, upload_to="jobs/"),
            preserve_default=False,
        ),
    ]
